<x-layout>
    <x-slot name="content">
        <div class="flex flex-col items-center justify-center p-4">
            <h1 class="text-4xl font-bold text-center p-4">About Me</h1>
            <p class="text-left w-3/4 mx-auto p-5">
                I am a highly motivated and enthusiastic individual with a passion for learning and growth. With several years of experience in my field, I have honed my skills and developed a strong understanding of the industry. I am constantly seeking new challenges and opportunities to expand my knowledge and skills. I have a strong work ethic and am committed to delivering high-quality results in a timely and efficient manner.
            </p>
            <p class="text-left w-3/4 mx-auto p-5">
                Aside from my professional life, I have a range of interests and hobbies that keep me engaged and inspired. Whether it's traveling to new destinations, practicing yoga, or exploring the outdoors, I believe that a well-rounded and balanced life is key to happiness and success. I am a firm believer in the power of positive thinking and strive to bring a positive and optimistic outlook to everything I do. I am eager to continue growing and learning, both professionally and personally, and am always open to new opportunities and experiences.
            </p>
            <p class="text-left w-3/4 mx-auto p-5">
                Content generated by ChatGPT-3
            </p>
        </div>
    </x-slot>
</x-layout>


{{-- flex items-center justify-center min-h-screen bg-gray-100  --}}